chore: try out windows main and agent jobs for unit and integration tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,9 +21,65 @@ env:
   NX_VERBOSE_LOGGING: true
 
 jobs:
-  main:
-    name: Nx Cloud - Main Job
-    runs-on: ubuntu-latest
+  # main:
+  #   name: Nx Cloud - Main Job
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: Derive appropriate SHAs for base and head for `nx affected` commands
+  #       uses: nrwl/nx-set-shas@v3
+
+  #     - name: Install primary node version (see volta config in package.json) and dependencies
+  #       uses: ./.github/actions/install-node-and-dependencies
+
+  #     - name: Run parallel distributed tasks
+  #       uses: jameshenry/parallel-bash-commands@v1
+  #       with:
+  #         cmd1: npx nx-cloud record -- npx nx format:check
+  #         cmd2: npx nx-cloud record -- npx nx workspace-lint
+  #         cmd3: npx nx run-many -t lint --parallel=3
+  #         cmd4: npx nx run-many -t test --parallel=3 --ci --maxWorkers=2
+
+  #     # e2e tests for everything except the primary task runner
+  #     - run: PUBLISHED_VERSION=999.9.9-e2e.0 npx nx run-many --target=run-e2e-tests-process --parallel=1
+
+  #     - name: Stop all running agents for this CI run
+  #       # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
+  #       if: ${{ always() }}
+  #       run: npx nx-cloud stop-all-agents
+
+  # agents:
+  #   name: Nx Cloud - Agent ${{ matrix.agent }}
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       agent: [1, 2, 3, 4]
+  #   steps:
+  #     - uses: actions/checkout@v3
+
+  #     - name: Configure git metadata
+  #       run: |
+  #         git config --global user.email test@example.com
+  #         git config --global user.name "Tester McPerson"
+
+  #     - name: Install primary node version (see volta config in package.json) and dependencies
+  #       uses: ./.github/actions/install-node-and-dependencies
+
+  #     - run: npm run e2e-start-local-registry
+
+  #     - run: NX_VERBOSE_LOGGING=true PUBLISHED_VERSION=999.9.9-e2e.0 npm run e2e-build-package-publish
+
+  #     - name: Start Nx Agent ${{ matrix.agent }}
+  #       run: npx nx-cloud start-agent
+  #       env:
+  #         NX_AGENT_NAME: ${{matrix.agent}}
+
+  windows-main:
+    name: Nx Cloud - Windows Main Job
+    runs-on: windows-latest
     steps:
       - uses: actions/checkout@v3
         with:
@@ -32,34 +88,39 @@ jobs:
       - name: Derive appropriate SHAs for base and head for `nx affected` commands
         uses: nrwl/nx-set-shas@v3
 
+      - name: Set Nx Run Group
+        run: |
+          echo "NX_RUN_GROUP=$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT-windows" >> $GITHUB_ENV
+          echo "NX_RUN_GROUP is ${{ env.NX_RUN_GROUP }}"
+
       - name: Install primary node version (see volta config in package.json) and dependencies
         uses: ./.github/actions/install-node-and-dependencies
 
-      - name: Run parallel distributed tasks
+      - name: Run distributed unit and integration tests on windows
         uses: jameshenry/parallel-bash-commands@v1
         with:
-          cmd1: npx nx-cloud record -- npx nx format:check
-          cmd2: npx nx-cloud record -- npx nx workspace-lint
-          cmd3: npx nx run-many -t lint --parallel=3
-          cmd4: npx nx run-many -t test --parallel=3 --ci --maxWorkers=2
+          cmd1: npx nx integration integration --ci --maxWorkers=2
+          cmd2: npx nx run-many -t test --parallel=3 --ci --maxWorkers=2
 
-      # e2e tests for everything except the primary task runner
-      - run: PUBLISHED_VERSION=999.9.9-e2e.0 npx nx run-many --target=run-e2e-tests-process --parallel=1
-
-      - name: Stop all running agents for this CI run
+      - name: Stop all running agents for this Nx Run Group
         # It's important that we always run this step, otherwise in the case of any failures in preceding non-Nx steps, the agents will keep running and waste billable minutes
         if: ${{ always() }}
         run: npx nx-cloud stop-all-agents
 
-  agents:
-    name: Nx Cloud - Agent ${{ matrix.agent }}
-    runs-on: ubuntu-latest
+  windows-agents:
+    name: Nx Cloud - Windows Agent ${{ matrix.agent }}
+    runs-on: windows-latest
     strategy:
       matrix:
         agent: [1, 2, 3, 4]
     steps:
       - uses: actions/checkout@v3
 
+      - name: Set Nx Run Group
+        run: |
+          echo "NX_RUN_GROUP=$GITHUB_RUN_ID-$GITHUB_RUN_ATTEMPT-windows" >> $GITHUB_ENV
+          echo "NX_RUN_GROUP is ${{ env.NX_RUN_GROUP }}"
+
       - name: Configure git metadata
         run: |
           git config --global user.email test@example.com
@@ -68,63 +129,59 @@ jobs:
       - name: Install primary node version (see volta config in package.json) and dependencies
         uses: ./.github/actions/install-node-and-dependencies
 
-      - run: npm run e2e-start-local-registry
-
-      - run: NX_VERBOSE_LOGGING=true PUBLISHED_VERSION=999.9.9-e2e.0 npm run e2e-build-package-publish
-
       - name: Start Nx Agent ${{ matrix.agent }}
         run: npx nx-cloud start-agent
         env:
-          NX_AGENT_NAME: ${{matrix.agent}}
+          NX_AGENT_NAME: ${{ matrix.agent }}
 
   # Isolated e2e tests for the task runner which become too flaky if nested through further node child processes
-  task-runner-e2e:
-    name: Task Runner E2E
-    runs-on: ubuntu-latest
-    env:
-      NX_CLOUD_DISTRIBUTED_EXECUTION: false
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  # task-runner-e2e:
+  #   name: Task Runner E2E
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     NX_CLOUD_DISTRIBUTED_EXECUTION: false
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
 
-      - name: Derive appropriate SHAs for base and head for `nx affected` commands
-        uses: nrwl/nx-set-shas@v3
+  #     - name: Derive appropriate SHAs for base and head for `nx affected` commands
+  #       uses: nrwl/nx-set-shas@v3
 
-      - name: Configure git metadata
-        run: |
-          git config --global user.email test@example.com
-          git config --global user.name "Tester McPerson"
+  #     - name: Configure git metadata
+  #       run: |
+  #         git config --global user.email test@example.com
+  #         git config --global user.name "Tester McPerson"
 
-      # TODO: figure out why uses: ./.github/actions/install-node-and-dependencies is causing pnpm to not be available in this job
-      - name: Install dependencies
-        run: npm ci
-        shell: bash
+  #     # TODO: figure out why uses: ./.github/actions/install-node-and-dependencies is causing pnpm to not be available in this job
+  #     - name: Install dependencies
+  #       run: npm ci
+  #       shell: bash
 
-      - name: Check if e2e-run-task-runner is affected
-        id: check_affected
-        run: |
-          IS_AFFECTED_STR=$(npx nx print-affected | jq '.projects | contains(["e2e-run-task-runner"])')
-          IS_AFFECTED=$([[ $IS_AFFECTED_STR == 'true' ]] && echo 'true' || echo '')
-          echo "is_affected=$IS_AFFECTED" >> $GITHUB_OUTPUT
-        shell: bash
+  #     - name: Check if e2e-run-task-runner is affected
+  #       id: check_affected
+  #       run: |
+  #         IS_AFFECTED_STR=$(npx nx print-affected | jq '.projects | contains(["e2e-run-task-runner"])')
+  #         IS_AFFECTED=$([[ $IS_AFFECTED_STR == 'true' ]] && echo 'true' || echo '')
+  #         echo "is_affected=$IS_AFFECTED" >> $GITHUB_OUTPUT
+  #       shell: bash
 
-      - name: Install pnpm
-        run: npm install -g pnpm
-        shell: bash
+  #     - name: Install pnpm
+  #       run: npm install -g pnpm
+  #       shell: bash
 
-      - run: pnpm --version
-        shell: bash
+  #     - run: pnpm --version
+  #       shell: bash
 
-      - name: Prepare e2e tests for task-runner
-        if: ${{ steps.check_affected.outputs.is_affected }}
-        run: npx nx prepare-for-e2e e2e-run-task-runner
-        shell: bash
+  #     - name: Prepare e2e tests for task-runner
+  #       if: ${{ steps.check_affected.outputs.is_affected }}
+  #       run: npx nx prepare-for-e2e e2e-run-task-runner
+  #       shell: bash
 
-      - name: Run e2e tests for task-runner
-        if: ${{ steps.check_affected.outputs.is_affected }}
-        run: e2e/run/task-runner/src/run-tests.sh
-        shell: bash
+  #     - name: Run e2e tests for task-runner
+  #       if: ${{ steps.check_affected.outputs.is_affected }}
+  #       run: e2e/run/task-runner/src/run-tests.sh
+  #       shell: bash
 
   # TODO: migrate to cacheable/distributable targets
   # test:
